// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/todos": {
            "get": {
                "description": "Retrieve all ToDos",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "todos"
                ],
                "summary": "Get ToDos",
                "responses": {
                    "200": {
                        "description": "Details of ToDos",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/helpers.Todo"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Creating a new ToDo",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "todos"
                ],
                "summary": "Add ToDo",
                "parameters": [
                    {
                        "description": "New ToDo",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/helpers.Todo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Details of the ToDo",
                        "schema": {
                            "$ref": "#/definitions/helpers.Todo"
                        }
                    }
                }
            }
        },
        "/todos/:id": {
            "delete": {
                "description": "Deleting the ToDo",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "todos"
                ],
                "summary": "Delete ToDo",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ToDo ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Details of the ToDo",
                        "schema": {
                            "$ref": "#/definitions/helpers.Todo"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "helpers.Todo": {
            "type": "object",
            "properties": {
                "Completed": {
                    "type": "boolean"
                },
                "ID": {
                    "type": "integer"
                },
                "Title": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "CRUD API",
	Description:      "A CRUD Backend API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
